export default function Sobre(){
    return(
        <div className="Sobre w-[1978px] h-[1359px] relative">
        <img className="Rectangle10 w-[430px] h-[406px] left-[65px] top-[134px] absolute" src="https://s3-alpha-sig.figma.com/img/5f3e/082c/32eb37331207b72a5327c4fb795ada1f?Expires=1702252800&Signature=fBJbcqektlUot91g3XR5RLB5ZxHnz0sWBur9jOf6WJmX96DXlEsvrSeM5A~6ADADRyf3z448H381ld71Z-ycAnKmzU-SG3-PY0S3gyKi7-D3I~ZkGGcfQH1fUBnE3SGbVu82Qm6XS-aUjq5WZV9eTxBXUxmsrl9l9y3LIeH6HDQEhrsB6vksSXG~IdVBqrYNVzn7th7FT~gLV3KqcZiU1yjFAuOm7TOh1pbODcVrmO-RTpKc9sO0UPDaR8R50zRQJCgQg9Zh3euABZ8VhHVhhefzC9h-V9fsUqRnSDrijmofveAmCaBu~3vNkfy0djA~61UClpVEfgHWZCJD0yksPg__&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4" />
        <img className="Rectangle11 w-[430px] h-[406px] left-[65px] top-[774px] absolute" src="https://s3-alpha-sig.figma.com/img/1279/61f4/38f213e0bd21b7d71470161d327db194?Expires=1702252800&Signature=Pl5EmgA8tcGUU5X4~dXyYP4mbN22nwdO28JFTT5y8EtUClEP31wjqQQJFavWeRbWhhsNLQ~NElynvbAAOqszxzq5kbIjffLqmrMsca2IyImXnwzbW2kVfmQcrEcENWI0gCl77i-VMWch60qVVKgNfgTbQvkIlEHgIqSv0fFrTE-dtDBuHgTl3ELV2EH1DvyMpziL5BKoKvFpe9mhKSAkWCz1W0mT7-SVSu6LvE5yzkncoD5CAc1toT8nk2IiC5VJYHg0TMq34CbVnyxPllDyClaHOqs2gnH1ztG~OACUi2alMsQ1hd9DLg4hBXBLXCIr1JDxBTlEfWA46c1TSLCL-Q__&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4" />
        <img className="Rectangle12 w-[430px] h-[406px] left-[1385px] top-[232px] absolute" src="https://s3-alpha-sig.figma.com/img/cf98/b4a6/cfed8cef901ebceff342e301471f0658?Expires=1702252800&Signature=pBrd0zI24jtrelNXksLOoQAKGeqrq-Rfqc3xRkj7rEEhHNhOEgtXsUgImhTf1fo2OfDRijfM6E~JXaba5oq54iUx2yUf5~UfuTANJMZNGDkLyzl8SSAIiZCaA4RBR3Pl816o196Kg2h3VK6uXHxW-Be5m~KSTI4Zda1PKNouE44Gm77V~o9awLfZyBAmRSsttrUUVcs4e3upst6rHM0dNNuQhK4WQS2Vk9iyEVo3WkH9F-liEURcnw6ku1wme94PCsZVjLbuBCGXC~6oxE0acp0BUveLIkhkk~oAOCHfcqViqCpKfuoFzezlNjf0qgfskTgdQDUEG1YGzMJZSHdpIA__&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4" />
        <div className="JavascriptUmaLinguagemDeProgramaODeAltoNVelLeveEInterpretadaDesenvolvidaOriginalmenteParaSerExecutadaNosNavegadoresWebElaPermiteACriaODePGinasWebInterativasEDinMicasAlMDissoOJavascriptAgoraUtilizadoEmVRiasOutrasPlataformasIncluindoServidoresComONodeJsAplicativosMVeisJogosEMuitoMais w-[677px] h-[171px] left-[552px] top-[864px] absolute text-black text-[32px] font-normal font-['Share'] uppercase">javaScript é uma linguagem de programação de alto nível, leve e interpretada. Desenvolvida originalmente para ser executada nos navegadores web, ela permite a criação de páginas web interativas e dinâmicas. Além disso, o JavaScript agora é utilizado em várias outras plataformas, incluindo servidores com o Node.js, aplicativos móveis, jogos e muito mais.</div>
        <div className="APrincipalFunODoCssSepararAEstruturaDoConteDoHtmlDaSuaApresentaOVisualIssoPermiteQueOsDesenvolvedoresApliquemEstilosConsistentesEmUmSiteOuAplicativoDaWebFacilitandoAManutenOEAAtualizaO w-[697px] h-[190px] left-[1273px] top-[702px] absolute text-black text-[32px] font-normal font-['Share'] uppercase">A principal função do CSS é separar a estrutura do conteúdo HTML da sua apresentação visual. Isso permite que os desenvolvedores apliquem estilos consistentes em um site ou aplicativo da web, facilitando a manutenção e a atualização.</div>
        <div className="ALinguagemPadrOParaACriaOEODesignDePGinasWebEAplicaEsWebEleUtilizadoParaEstruturarOConteDoDeUmaPGinaDaWebUsandoUmaSintaxeDeMarcaOCompostaPorElementosOuTagsQueDescrevemDiferentesPartesDoConteDo w-[502px] h-[296px] left-[552px] top-[204px] absolute text-black text-[32px] font-normal font-['Share'] uppercase">é a linguagem padrão para a criação e o design de páginas web e aplicações web. Ele é utilizado para estruturar o conteúdo de uma página da web usando uma sintaxe de marcação composta por elementos (ou tags) que descrevem diferentes partes do conteúdo.</div>
    </div>
    )
}