export default function Footer(){
    return(
        <div className="Main w-[1978px] h-[1412px] relative">
        <div className="Main w-[1978px] h-[1412px] left-0 top-0 absolute bg-gradient-to-b from-neutral-50 to-zinc-600 border border-black" />
        <div className="SobreMim left-[169px] top-[109px] absolute"><span className="text-black text-9xl font-normal font-['Share'] uppercase">S</span><span className="text-black text-5xl font-normal font-['Share'] uppercase">OBRE </span><span className="text-black text-9xl font-normal font-['Share'] uppercase">M</span><span className="text-black text-5xl font-normal font-['Share'] uppercase">IM</span></div>
        <div className="UmApaixonadoDesenvolvedorWebECriadorIncansVelDeExperiNciasOnlineInovadorasComUmaPaixOPorTransformarIdeiasEmRealidadeDigitalTenhoDedicadoMinhaCarreiraAoDesenvolvimentoDeSitesQueNOApenasImpressionamVisualmenteMasTambMProporcionamUmaExperiNciaExcepcionalAosUsuRios w-[1092px] h-[406px] left-[146px] top-[264px] absolute"><span className="text-black text-5xl font-normal font-['Share'] uppercase tracking-[3.84px]">um apaixonado desenvolvedor web e criador incansável de experiências online inovadoras. Com uma paixão por transformar ideias</span><span className="text-black text-5xl font-normal font-['Share'] uppercase tracking-widest"> </span><span className="text-black text-5xl font-normal font-['Share'] uppercase tracking-[3.84px]">em realidade digital, tenho dedicado minha carrei</span><span className="text-black text-5xl font-normal font-['Share'] uppercase tracking-[5.28px]">r</span><span className="text-black text-5xl font-normal font-['Share'] uppercase tracking-[3.84px]">a ao desenvolvimento de sites que não apenas impressionam visualmente, mas também proporcionam uma experiência excepcional aos usuários.</span></div>
        <img className="Ellipse1 w-[729px] h-[716px] left-[1213px] top-[109px] absolute rounded-full" src="https://s3-alpha-sig.figma.com/img/5c01/8ba9/dd59dfa47dc13c21c17ee269f11e2581?Expires=1702252800&Signature=W9GIJJCPGWRzp-mNbnQZ4RhVxjSngw79SzPBZVeSw2AIVcZQS3Vwfbbwai7VXb9LV0F5wTPnAzjYmbbHFiwT8N~n25SAAq20cSzmQAWRdl-OkEDKOYmZ7Q0PQ2V2r~l-wGKDVVtWEscFxiL6bGdzoaMkjrl3mSOzcHUPrbJCnU0EHzBgN6gLSewxoFIzZZhNqwe2wVqFV6ehxc9R9sBNiAgE6nCB5yDMf0n9crW3597y3iSE7q429uR1FKh-qPDy-YDR87IPpw2nnMgymByWSlqgIO9bzmn4f9D5QrzZRg5ibzAVw31KEDnVuhWdSDCX~FURC6968DlPdrStzbhDBQ__&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4" />
        <div className="MinhaJornadaNoMundoDigitalAbrangeUmaVastaGamaDeHabilidadesTCnicasDesdeAProgramaOFrontEndAtOBackEndTenhoDominadoLinguagensComoHtmlCssJavascriptEEstouSempreAtualizadoComAsLtimasTendNciasETecnologiasGarantindoQueMeusProjetosEstejamNaVanguardaDaInovaO w-[1764.88px] h-[416.92px] left-[143px] top-[815.82px] absolute"><span className="text-black text-5xl font-normal font-['Share'] uppercase tracking-[5.28px]">Minha jornada no mundo digital abrange uma<br/>vasta gama de habilidades técnicas. Desde a programação front-end até o back-end, tenho dominado linguagens como HTML, CSS, JavaScript, e estou sempre atualizado com as últi</span><span className="text-black text-5xl font-normal font-['Share'] uppercase tracking-[3.84px]">m</span><span className="text-black text-5xl font-normal font-['Share'] uppercase tracking-[5.28px]">as tendências e tecnologias, garantindo que meus projetos estejam na vanguarda da inovação.</span></div>
        <div className="Aleatorioofcbr left-[462px] top-[1346px] absolute text-white text-4xl font-normal font-['Share'] uppercase">aleatorioofcbr</div>
        <div className="Aleatorio w-[254px] h-[50px] left-[960px] top-[1346px] absolute"><span className="text-white text-[40px] font-normal font-['Share'] uppercase">@</span><span className="text-white text-4xl font-normal font-['Share'] uppercase">aleatorio</span></div>
        <div className="AleatorioGmailCom left-[1367px] top-[1346px] absolute text-white text-4xl font-normal font-['Share'] uppercase">aleatorio@gmail.com</div>
        <div className="Facebook w-12 h-12 left-[404px] top-[1339px] absolute" />
        <div className="Email w-12 h-12 left-[1319px] top-[1342px] absolute" />
        <div className="Instagram w-12 h-12 left-[912px] top-[1342px] absolute" />
    </div>
    )
}